#!/bin/bash
# Deepseek成本跟踪系统验证提醒 - 早上7:00

echo "⏰ **早上7:00提醒**"
echo "================================"
echo ""
echo "🛠️ **Deepseek成本跟踪系统需要验证**"
echo ""
echo "请在Terminal中运行以下命令："
echo ""
echo "1. 首先进入工作目录："
echo "   cd /Users/zhaoyuzhao/.openclaw/xiaofeng_workspace"
echo ""
echo "2. 生成成本报告："
echo "   ./start_deepseek_tracker.sh report"
echo ""
echo "3. 运行集成测试："
echo "   python3 test_deepseek_integration.py"
echo ""
echo "4. 如果有问题，启动监控模式："
echo "   ./start_deepseek_tracker.sh monitor"
echo ""
echo "📋 **验证要点**："
echo "- 检查API调用是否正确拦截"
echo "- 确认成本记录到数据库"
echo "- 验证报告生成正常"
echo ""
echo "⏰ 提醒时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo "🔧 任务: Deepseek成本跟踪系统验证"