#!/usr/bin/env python3
"""V2: 使用 Playwright stealth 获取 Douyin 新鲜 cookies"""
import sys, json, os, tempfile, time

def get_douyin_cookies(output_path: str = None) -> str:
    from playwright.sync_api import sync_playwright
    
    cookie_file = output_path or os.path.join(tempfile.gettempdir(), "douyin_cookies.txt")
    
    with sync_playwright() as p:
        # Use non-headless or better args to avoid detection
        browser = p.chromium.launch(
            headless=True,
            args=[
                '--disable-blink-features=AutomationControlled',
                '--no-sandbox',
                '--disable-web-security',
                '--disable-features=IsolateOrigins,site-per-process',
            ]
        )
        context = browser.new_context(
            user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            viewport={"width": 1440, "height": 900},
            locale="zh-CN",
            timezone_id="Asia/Shanghai",
        )
        # Remove webdriver detection
        context.add_init_script("""
            Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
            Object.defineProperty(navigator, 'plugins', {get: () => [1, 2, 3, 4, 5]});
            Object.defineProperty(navigator, 'languages', {get: () => ['zh-CN', 'zh', 'en']});
            window.chrome = {runtime: {}};
        """)
        
        page = context.new_page()
        
        try:
            # Load homepage with longer wait
            page.goto("https://www.douyin.com", wait_until="domcontentloaded", timeout=45000)
            time.sleep(5)
            # Navigate to discovery page to trigger more interactions
            page.goto("https://www.douyin.com/discover", wait_until="domcontentloaded", timeout=45000)
            time.sleep(3)
        except Exception as e:
            print(f"[COOKIE] Warning: {e}", file=sys.stderr)
        
        cookies = context.cookies()
        browser.close()
        
        if len(cookies) < 5:
            print("[COOKIE] Too few cookies, likely blocked!", file=sys.stderr)
            return ""
        
        with open(cookie_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by douyin_cookie_fetcher\n")
            for c in cookies:
                domain = c.get('domain', '.douyin.com')
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                secure = 'TRUE' if c.get('secure', False) else 'FALSE'
                expires = str(int(c.get('expires', -1))) if c.get('expires', -1) > 0 else '0'
                f.write(f"{domain}\t{flag}\t{c.get('path','/')}\t{secure}\t{expires}\t{c.get('name','')}\t{c.get('value','')}\n")
        
        print(f"[COOKIE] {len(cookies)} cookies → {cookie_file}", file=sys.stderr)
        return cookie_file

if __name__ == "__main__":
    path = get_douyin_cookies(sys.argv[1] if len(sys.argv) > 1 else None)
    print(path if path else "")
    sys.exit(0 if path else 1)
